### ISSUE TITLE
test own picture

### ISSUE THREAD

**Issue by ke-s** [lidq92/SFA#11]
When I am researching the test_demo.py you giving found that the model exists in the VSFA,CNNIQA,WaDIQaM you gave, however this code does not save this model,How should I test blur images of myself without subjective scoring ?
Does the sfa file you give is a training code or a test code?

**Comment by lidq92** [comment]
If your dataset does not contain subjective scores, you need to train the PLSR model on a rated dataset, e.g., BID/CLIVE, etc.
The code I provided can be used to train the PLSR model. You can just make a little modification to save the PLSR model parameters and then use them in your test scripts.

**You can use the Demo.m for testing if you are using MATLAB**.
Otherwise, if you are using python and pytorch, you need to make a little modification of the code to save the PLSR models.

I do not intend to write one more test demo (for PyTorch version) since **the official code is based on MATLAB**. 
However, there is a lot of references (See #4 #5) you can refer to. 
I am busy now, and it would be beneficial for you if you write it by yourself.
