### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by liang23333** [lidq92/SFA#2]
Hi, when test using your code, i have met these problems. Could you give me some suggestions?

1. F1113 20:51:42.569744 38502 upgrade_proto.cpp:95] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: /home/liang/caffe/matlab/SFA/models/ResNet-50-model.caffemodel

2. This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.
** This crash report has been saved to disk as /home/liang/matlab_crash_dump.38344-1 *

------------------------------

When i search in google, some people says that the reason of Question1 is due to the error of caffemodel. But i download the caffemodel on the https://github.com/KaimingHe/deep-residual-networks.

Others say that the error is due to multi-gpu. But i use caffe.set_device(0), this problem still exists. How do you think?

Moreover, could you provide the dataset of  BID and CLIVE, it is difficult to get on the internet.

**Comment by liang23333** [comment]
Could you provide your code and models via baiduNetdisk or other methods?

**Comment by lidq92** [comment]
@liang23333 It has been a long time since the last time I used Caffe. Sorry for no good suggestion for your problem.

1. I guess the first problem arises due to the version of Caffe (I previous used v1.0 for this work.)
2. Where is your MEX-file? If in your Caffe, then refer to the above comment.
3. I did not use multi-GPU in the experiments of this work.
4. My code for this work is the same as you see in this repo. I provide an alternative download URL for the caffemodel file (See `Readme.md`).

Overall, my suggestion is to ensure you have the same environments as my experiments. At least you should try to use Caffe 1.0 and MATLAB 2016b.

As for the datasets, you can get them [here](https://pan.baidu.com/s/10rGDziwuQl0fjwDHlhX1dA) with password `b6sv`.

**New!** I have also provided a [PyTorch implementation of this method](https://github.com/lidq92/SFA/tree/master/SFA-pytorch) (for simplicity), you can go for it (It should be noted that the results reported in the paper are obtained using Caffe+MATLAB).

Good luck!

**Comment by liang23333** [comment]
Thank you very much for your help!!!

**Comment by lidq92** [comment]
@liang23333 Caffemodel BaiduNetDisk sharing is now available [here](https://pan.baidu.com/s/1T32sYjrQA04kl1auArirxw) with password `u8sd`

**Comment by liang23333** [comment]
@lidq92  I think i have known where the error is, the caffemodel i downloaded is about 80M, but the mdoel is provide is 97M. Thank you for your help.
